# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv'
Dotenv.load('../../.env')

default_platform(:android)

platform :android do
  desc "Lane for  Android App Distribution" 
  
  lane :dev do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV['FIREBASE_ANDROID_APP_ID']
    )
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons --build-number=#{latest_release[:buildVersion].to_i + 1}"
    release =  firebase_app_distribution(
      app: ENV['FIREBASE_ANDROID_APP_ID'],
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "mohamedmaher.personal@gmail.com",
      release_notes: "test release notes",
    )
  end

  lane :stage do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    release =  firebase_app_distribution(
      app: ENV['FIREBASE_ANDROID_APP_ID'],
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: "app_testers",
      release_notes: "test release notes",
    )
  end
end